name: glacier-flow-tools
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - mpich-mpicxx
  - setuptools
  - pre-commit
  - pytest
  - gsl
  - mypy
  - pylint
  - pip
  - pip:
      - -r requirements.txt
