name: glacier-flow-tools
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - cython
  - mpich-mpicxx
  - setuptools
  - pre-commit
  - gsl

  # for development and testing
  - black
  - isort
  - mypy
  - pylint
  - pytest
  - pytest-cov
  - setuptools_scm>=6.2

  # for docs
  - ipykernel
  - myst-nb
  - numpydoc
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-book-theme>=1.0
  - sphinx-copybutton
  - sphinx-design
  - sphinx-gallery
  - sphinxcontrib-programoutput

  - pip
  - pip:
      - -r requirements.txt
