name: glacier-flow-tools
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - cython
  - mpich-mpicxx
  - setuptools
  - pre-commit
  - gsl

  # Testing
  - pytest
  - pytest-cov
  - mypy
  - pylint

  - pip
  - pip:
      - -r requirements.txt
