name: glacier-flow-tools
channels:
  - bioconda
  - conda-forge
dependencies:
  - cytoscape
  - ipycytoscape
  - pre-commit
  - pytest
  - mypy
  - pylint
  - pip
  - pip:
      - -r requirements.txt
